### PR TITLE
Arg list add kwargs

### LINKED ISSUE #112: Argument list does not contain arguments parsed by `cmake_parse_arguments`
**Is your feature request related to a problem? Please describe.**
CMinx documents the parameter list of a CMake function. However, by CMake's nature, additional unnamed arguments can always be passed to a function. Usually, these are then parsed by `cmake_parse_arguments`. However, it's confusing to read the documentation of a function with named arguments that accepts additional parameters. Take this example (excerpt from the docs):

```rst
.. function:: advanced_say_hi_to(me)
   
   :param me: The name of the person saying hi.
   :keyword PERSONS: The person or persons to say hi to.
```

**Describe the solution you'd like**
I realize this is a stretch but it would be really great if CMinx could detect the call to `cmake_parse_arguments` in the function body and then automatically add an indicator that the function may take additional arguments. I would like the result to look something like

```rst
.. function:: advanced_say_hi_to(me *args)
   
   :param me: The name of the person saying hi.
   :keyword PERSONS: The person or persons to say hi to.
```
Notice the `*args` (or something similar) as new indicator.

**Describe alternatives you've considered**
Alternatively, the `*args` could simply be added if a keyword/parameter specified in the comment block does not appear in the function signature.

**Additional context**
None

### PR DESCRIPTION
**Pull request by AutonomicPerfectionist**
**Is this pull request associated with an issue(s)?**
Fixes #112

**Description**
This PR adds support for auto-parsing CMake `parse_arguments()` calls to determine whether keyword or additional 
arguments are expected, then adds documentation for them if it does not exist.

**TODOs**

- [x] Add processor for parse_arguments()
- [x] Add stack for function/macro definitions being processed to know where we are in the parse tree
- [x] Process args to `parse_arguments()` and add results to function or macro documentation in the stack
- [x] Add unit tests
- [x] Add documentation
- [x] Fix interplay with nested undocumented functions

### CODE REVIEW

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist can you do me a favor and update the master branch you're basing your PRs off of? I think it still has the `VERSION.txt` file in it and I end up deleting it from your PRs to avoid putting it back into master.

**Comment by AutonomicPerfectionist** [comment]
> @AutonomicPerfectionist can you do me a favor and update the master branch you're basing your PRs off of? I think it still has the `VERSION.txt` file in it and I end up deleting it from your PRs to avoid putting it back into master.

Whoops, for some reason merging with upstream left that file intact, I've deleted it manually now

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard this PR now has basic support for autodetecting `cmake_parse_arguments()`, right now all it does is generate an additional `**kwargs` argument in the function or macro signature if it detects the usage of that command. What other functionality was requested? Also this PR is not quite ready for review because there's some weird interplay with undocumented nested functions, working on that right now

**Comment by ryanmrichard** [comment]
The other suggested functionality was to parse the doc comment to determine if the user has documented keywords using the `:keyword xxx:` role. The motivation here is that downstream we actually write a wrapper around `cmake_parse_arguments` that does type checking, so looking for `cmake_parse_arguments` won't be called directly.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I've added the requested functionality, but from what I can tell the `:keyword:` sphinx role is for linking to Python keywords like `is` or `class`, not for keyword arguments. For now, I'm just searching the docstring for `**kwargs` but it's easy to change, at the very least CMakeTest uses `:param **kwargs:` to document its keyword arguments if we want to search for that pattern

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist I now think you're correct and that `:keyword:` is not meant for this purpose (although I can't seem to find any examples using it the way you describe either). I think it's best if we make this feature configurable, i.e., let the user tell us what string they use to denote kwargs and default it to `:param **kwargs:` to be consistent with CMakeTest. We also should update the documentation so it no longer recommends using `:keyword:` for this situation.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard looking into it further it seems I was somewhat mistaken: some projects use `:param *kwargs*:` with a list of the arguments below that, and some projects use `:keyword:`, for example, PyInstaller and PyTest. I think the confusion stems from a lack of clear guidelines on the Python side over its long history on how to document keyword arguments, but at the very least there does seem to be precedent for using `:keyword:`. In my opinion, it looks and feels cleaner to use the `:keyword:` method, and thanks to the configurability we implemented it was easy to revert to it. I've updated the documentation as well. If defaulting to `:keyword:` is alright with you I think this PR is ready for review.

There is a failing workflow for release testing, but I think that has to do with the action itself not being configured correctly. I'll look into it

**Review by ryanmrichard — DISMISSED** [review]
Looks great! Thanks!

**Comment by AutonomicPerfectionist** [comment]
Looks like the failing `test_pypi` action is due to the `ubuntu-latest` runner upgrading to Ubuntu 22.04, which has some bug with the pip installation, I found a possibly related bug report here: https://github.com/pypa/pip/issues/6264. A more permanent fix would be to do the installation and test runs inside a virtual env without `--site-packages`

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist I'm fine dropping back to Ubuntu 20.04 for now. 

I don't follow the `--site-packages` problem. Based on GitHub's search feature I can't find anywhere in the CMakePP organization where we use `--site-packages`. I'm not sure I understand the `--site-packages` flag either; does it just say that the virtual environment has access to system-wide Python packages? 

Are you saying [this](https://github.com/CMakePP/.github/blob/main/.github/workflows/pypi_release_master.yaml) should be done in a virtual environment?

**Comment by ryanmrichard** [comment]
Also it looks like this PR adds one untested line of code. Is it possible to update the tests to keep the code coverage the same?

**Comment by AutonomicPerfectionist** [comment]
> I don't follow the `--site-packages` problem. Based on GitHub's search feature I can't find anywhere in the CMakePP organization where we use `--site-packages`. I'm not sure I understand the `--site-packages` flag either; does it just say that the virtual environment has access to system-wide Python packages?

Yes, it just says the virtual environment can access the system-wide packages, we don't currently use it but the issue with the test_release workflow has to do with the system-installed packages on the ubuntu 22.04 runner. So we need to make a virtual environment to run the tests in and make sure it doesn't access those packages since it would then have the same issue. I can verify the fix later this week on a different branch/PR

As for the test coverage, yeah I can fix that, I just have finals this week and didn't notice the test coverage until I was busy studying, should be fixed around Wednesday or Thursday

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard got the coverage to pass, needed to add additional unrelated tests but everything is passing now

**Review by ryanmrichard — APPROVED** [review]

**Comment by ryanmrichard** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/CMakePP/CMinx/actions/runs/3733002112) **New version**:[v1.1.0](https://github.com/CMakePP/CMinx/releases/tag/v1.1.0) **Changes**:[v1.0.13...v1.1.0](https://github.com/CMakePP/CMinx/compare/v1.0.13...v1.1.0)

**Pull request merged**
