### PR TITLE
Settings object and file

### LINKED ISSUE #76: Settings File
**Is your feature request related to a problem? Please describe.**
CMinx is starting to get a lot of settings. Setting them all as part of the command leads to a long invocation.

**Describe the solution you'd like**
It'd be good if we could use a JSON/YAML file for setting options with options to the command taking precedence.

List of settings that have come up so far:

- output format (depends on #78 being viable)
- whether or not to include undocumented functions, variables, etc. (maybe one setting each?)
- Should we strip file extensions from the titles?
- character used in separating folders and files in a page's title (right now we use periods similar to Python, but could use slashes to mirror how CMake's `include` actually works).
- #66 probably falls under this too.

Other thoughts:

- RST title delimiter character order (thinking [this](https://github.com/CMakePP/CMinx/blob/master/cminx/rstwriter.py#L33))
- may as well include output directory as a setting

### PR DESCRIPTION
**Pull request by AutonomicPerfectionist**
**Is this pull request associated with an issue(s)?**
Fixes #76

**Description**
This PR centralizes configuration settings in a combination of a `config_defaults.yaml` file and any user-specified YAML files. It establishes a hierarchy of priority between defaults, user-specified settings files, and command-line flags.

**TODOs**

- [x] Make command-line flags automatically override config settings
- [x] Pass config settings between the various layers of CMinx, from the command-line interface layer all the way down the parser and aggregator layer.
- [x] Ensure config_default.yaml contains all the needed settings upon loading
- [x] Ensure config_default.yaml is packaged with the rest of the data files and is readable during execution
- [x] Add support for missing options
- [x] Add tests

### CODE REVIEW

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I have a preliminary format for the INI configuration file, does this look adequate or would a different format or layout suit it better?

https://github.com/AutonomicPerfectionist/CMakeDoc/blob/cd29f865dd3b66066b9e4efae54819185ac36027/defaults.ini

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist The literal options look good, but AFAIK INI files are a Windows thing. Most of the people I work with are Mac or Linux, so I think a more universal format like JSON/YAML would be preferred. That said INI format really isn't too hard to pick-up, so if there's no Python library out there for JSON/YAML-based config files I think going with INI is better than rolling our own solution.

**Comment by AutonomicPerfectionist** [comment]
> @AutonomicPerfectionist The literal options look good, but AFAIK INI files are a Windows thing. Most of the people I work with are Mac or Linux, so I think a more universal format like JSON/YAML would be preferred. That said INI format really isn't too hard to pick-up, so if there's no Python library out there for JSON/YAML-based config files I think going with INI is better than rolling our own solution.

@ryanmrichard I chose INI because Python's standard library includes a `configparser` package that works with a dialect of it and because it's so simple. In order to use YAML or JSON, an additional library dependency would need to be added, but in my opinion it would be worth it.

For defaults, do you think a separate `defaults.yml` file should be used, or hardcode it into the program as a `dict`?

**Comment by ryanmrichard** [comment]
It's weird to me that Python's native library would use a Windows format, but maybe it made sense at the time. Regardless, I think it's fine to add another dependency to get JSON or YAML support.

**Comment by ryanmrichard** [comment]
> For defaults, do you think a separate defaults.yml file should be used, or hardcode it into the program as a dict?

I think I misunderstood the question. If you're talking about CMinx's defaults I'd hardcode them. If you're talking about the user's defaults then see my last comment.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard this one is pretty much ready to go, minus the code coverage thing again. I can write additional tests to get that up next week.

For handling the YAML config files I decided on the Confuse library, as it has strong templating support to ensure config keys or values were not mistyped. It also works well with overlaying views, and searches operating system configuration paths automatically.

Additionally, the Python logging configuration was able to be entirely embedded in the application YAML, so a very wide array of logging settings is available.

**Review by ryanmrichard — APPROVED** [review]

**Comment by ryanmrichard** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/CMakePP/CMinx/actions/runs/2641296734) **New version**:[v0.1.0](https://github.com/CMakePP/CMinx/releases/tag/v0.1.0) **Changes**:[v0.0.6...v0.1.0](https://github.com/CMakePP/CMinx/compare/v0.0.6...v0.1.0)

**Pull request merged**
