### PR TITLE
Clean up code

### LINKED ISSUE #99: Clean up code for 1.0 release
**Is your feature request related to a problem? Please describe.**
The code is a bit messy in places and should be cleaned up.

### PR DESCRIPTION
**Pull request by AutonomicPerfectionist**
**Is this pull request associated with an issue(s)?**
Fixes #99 

**Description**
This PR adds inline comments and refactors code to be more idiomatic and pythonic.

**TODOs**

- [x] Move documenter processing methods into each documentation type's `process()` method
- [x] Refactor `ClassDocumentation` to better handle inner documentation
- [x] Finish adding type hints
- [x] Check all files for updated documentation, both docstrings and inline comments
- [x] Adjust for #98 to avoid excessive merge conflicts

### CODE REVIEW

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist Unless you feel differently, I vote that merging this PR results in  1.0. Unfortunately, my guess is the PyPI upload of that 1.0 will fail because when I was messing around with PyPI packaging I pushed a release and tagged it as 1.0. I subsequently learned that PyPI is crazy strict with versioning and now that we've called something "CMinx 1.0", that's our 1.0 forever (FWIW I've now also learned that there's "Test PyPI" to practice deploying to PyPI). Anyways, long story short, once this PR gets merged we'll need to actually make a 1.1 release to get the PyPI releases going.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I agree that this PR should result in 1.0, as far as I'm aware there aren't any other outstanding issues other than #80. Does that one require the 1.0 release to be finalized before it can be fixed?

**Comment by ryanmrichard** [comment]
80 can be done after the 1.0. It's not very important.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I think this one is ready for review now. Let me know if there's anything you want to be changed before we merge

**Review by ryanmrichard — APPROVED** [review]
lgtm

**Comment by ryanmrichard** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/CMakePP/CMinx/actions/runs/2820674090) **New version**:[v1.0.0](https://github.com/CMakePP/CMinx/releases/tag/v1.0.0) **Changes**:[v0.1.4...v1.0.0](https://github.com/CMakePP/CMinx/compare/v0.1.4...v1.0.0)

**Pull request merged**
