### PR TITLE
Pep8 format

### LINKED ISSUE #88: Format according to PEP8
**Is your feature request related to a problem? Please describe.**
Python has a very specific format specification described in [Python Enhancement Proposal 8](https://peps.python.org/pep-0008/). Nowadays this specification is considered the standard Python code format, and most IDEs support autoformatting files to PEP8.

**Describe the solution you'd like**
A quick format using autoPEP8 or an IDE equivalent, and adherence to the standard for future code additions.

**Describe alternatives you've considered**
We could come up with our own formatting rules and implement them as a custom formatter profile. However this would introduce significant effort to create the profiles for each major IDE or tool, for minimal benefits compared to using PEP8

### PR DESCRIPTION
**Pull request by AutonomicPerfectionist**
**Is this pull request associated with an issue(s)?**
Fixes #88 

**Description**
Reformats all Python code according to PEP8

### CODE REVIEW

**Review by ryanmrichard — DISMISSED** [review]
Disclaimer: I didn't read this; I'm trusting it's all just formatting

**Comment by AutonomicPerfectionist** [comment]
> Disclaimer: I didn't read this; I'm trusting it's all just formatting

Sorry, one of the automated changes broke a test so I'm fixing that quick. Also, since some of the lines were broken up into multiple Codecov thinks coverage has gone down slightly so I may have to write an additional test to get that back up

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard unfortunately I've ran out of time for now, everything looks good to me for review except that codecov is still complaining. I can write another test later if desired though

**Review by ryanmrichard — APPROVED** [review]

**Comment by ryanmrichard** [comment]
I'm fine with the slight drop in code coverage.

**Pull request merged**
