### PR TITLE
Version from Git

### PR DESCRIPTION
**Pull request by ryanmrichard**
**Is this pull request associated with an issue(s)?**
No

**Description**
Previously we had been using the `version.txt` (and more recently `VERSION.txt`) file to store the version. With the `tag_and_release` workflow we now have a GitHub action which will automatically tag each version for us. This PR deletes `VERSION.txt` and updates `CMakeLists.txt` and `docs/source/conf.py` so that they use the current Git tag.

**TODOs**
- [x] apparently git appends the SHA to the tag after you commit, that's annoying. Need to remove it.
- [x] @AutonomicPerfectionist Do you see any reason why we'd actually still need the `VERSION.txt` file?

### CODE REVIEW

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard `version.txt` was used to synchronize version information between the CMake interface and the Python package. It looks like the Python half was not updated to use the all-caps version of the file, nor to get the version from git. The code for the python part can be found here:

https://github.com/CMakePP/CMinx/blob/f21e04f00914f60465697bd87cf5320c9bd565d1/setup.py#L21-L26

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist `setup.py` now uses git for the version too. It feels a bit janky to use subprocess, but I couldn't for the life of me get the tagging action to update the `VERSION.txt` file (the action says it succeeded, but the push is actually rejected by GitHub because master is protected; I tried making a personal access token with admin privileges and adding myself to the exception list, but it still got rejected)

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard looks good to me

**Comment by ryanmrichard** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/CMakePP/CMinx/actions/runs/2496250461) **New version**:[v0.0.5](https://github.com/CMakePP/CMinx/releases/tag/v0.0.5) **Changes**:[v0.0.4...v0.0.5](https://github.com/CMakePP/CMinx/compare/v0.0.4...v0.0.5)

**Pull request merged**
