### PR TITLE
Action for Formatting to PEP8

### PR DESCRIPTION
**Pull request by ryanmrichard**
**Is this pull request associated with an issue(s)?**
No

**Description**
PEP8 is arguably the de facto way to format Python scripts. This PR adds a workflow which will run on this (and every PR). The workflow:

- Pulls the repo
- Runs `autopep8` on the `cminx/` directory
- Pushes any formatting changes back to the RP

**TODOs**
None. This is r2g assuming it works as intended.

### CODE REVIEW

**Comment by ryanmrichard** [comment]
This is r2g. The commit with CI notes uses the formatted code to make sure the formatting didn't break anything.

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist My guess is it has something to do with the automatic commit. I just merged master (and the formatted version of this branch), let's see what CI say.

**Comment by ryanmrichard** [comment]
Based on the CI logs, there's a warning about no data being collected, which is presumably why it's getting 0%. Not sure why no data has been collected; looking into that now...

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist I fixed it. It looks like applying PEP8 formatting to `test_parser.py` was the problem. For the time being I disabled formatting the `tests/` directory. I'm not sure what's causing the drop in coverage (maybe just more lines?), but I'm not too worried about it for the purposes of this PR. You okay merging it?

**Review by AutonomicPerfectionist — APPROVED** [review]

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard looks good to me

**Pull request merged**
